import { additionalCalculators } from "@/lib/additional-calculators";

export type FieldKind = "currency" | "number" | "percent";
export type OutputKind = "currency" | "number" | "percent" | "multiple";

export type CalculatorField = {
  key: string;
  label: string;
  kind: FieldKind;
  defaultValue: number;
  help: string;
  step?: number;
  min?: number;
};

export type CalculatorOutput = {
  label: string;
  value: number;
  kind: OutputKind;
  helper: string;
};

export type ExampleItem = {
  label: string;
  value: string;
};

export type CalculatorDefinition = {
  slug: string;
  name: string;
  icon: string;
  description: string;
  metaDescription: string;
  formula: string;
  formulaNote: string;
  fields: CalculatorField[];
  example: {
    summary: string;
    inputs: ExampleItem[];
  };
  faq: {
    question: string;
    answer: string;
  }[];
  relatedSlugs: string[];
  compute: (values: Record<string, number>) => CalculatorOutput[];
};

const toNumber = (value: number) => (Number.isFinite(value) ? value : 0);
const safeDivide = (numerator: number, denominator: number) =>
  denominator === 0 ? 0 : numerator / denominator;

export const calculators: CalculatorDefinition[] = [
  {
    slug: "roas",
    name: "ROAS Calculator",
    icon: "📈",
    description: "Measure how much revenue your ads generate for every dollar spent.",
    metaDescription:
      "Calculate ROAS in real time, see net profit, and understand the revenue return from every advertising dollar.",
    formula: "ROAS = Revenue / Ad Spend",
    formulaNote:
      "A ROAS of 4.5x means every $1 of ad spend generated $4.50 in revenue.",
    fields: [
      {
        key: "adSpend",
        label: "Ad spend",
        kind: "currency",
        defaultValue: 1000,
        help: "Enter the total amount you spent on the campaign.",
        step: 10,
        min: 0,
      },
      {
        key: "revenue",
        label: "Revenue",
        kind: "currency",
        defaultValue: 4500,
        help: "Enter the attributed revenue generated by the campaign.",
        step: 10,
        min: 0,
      },
    ],
    example: {
      summary: "If you spend $1,000 and generate $4,500 in revenue, your ROAS is 4.5x.",
      inputs: [
        { label: "Ad spend", value: "$1,000" },
        { label: "Revenue", value: "$4,500" },
      ],
    },
    faq: [
      {
        question: "What is a good ROAS?",
        answer:
          "A good ROAS depends on your margins. The key benchmark is break-even ROAS, which tells you the minimum return you need to stay profitable.",
      },
      {
        question: "Is ROAS the same as ROI?",
        answer:
          "Not exactly. ROAS compares revenue to ad spend, while ROI compares profit to total investment. ROAS is the more common ad platform metric.",
      },
      {
        question: "How can I improve ROAS?",
        answer:
          "Tighten targeting, refresh creative, improve landing pages, and cut wasteful spend on low-performing audiences or keywords.",
      },
    ],
    relatedSlugs: ["break-even-roas", "cpa", "facebook-ads-cost"],
    compute: ({ adSpend, revenue }) => {
      const roas = safeDivide(revenue, adSpend);
      return [
        {
          label: "ROAS",
          value: toNumber(roas),
          kind: "multiple",
          helper: "Revenue returned for every $1 spent.",
        },
        {
          label: "Return",
          value: toNumber(roas * 100),
          kind: "percent",
          helper: "Revenue shown as a percentage of ad spend.",
        },
        {
          label: "Net profit",
          value: toNumber(revenue - adSpend),
          kind: "currency",
          helper: "Revenue minus ad spend.",
        },
      ];
    },
  },
  {
    slug: "cpa",
    name: "CPA Calculator",
    icon: "💸",
    description: "Work out your cost per acquisition from total spend and acquired customers.",
    metaDescription:
      "Calculate cost per acquisition instantly and see how efficiently your campaigns turn spend into new customers or leads.",
    formula: "CPA = Ad Spend / Acquisitions",
    formulaNote:
      "CPA helps you compare channel efficiency when your goal is leads, sales, or signups.",
    fields: [
      {
        key: "adSpend",
        label: "Ad spend",
        kind: "currency",
        defaultValue: 1200,
        help: "Total campaign spend across the reporting window.",
        step: 10,
        min: 0,
      },
      {
        key: "acquisitions",
        label: "Acquisitions",
        kind: "number",
        defaultValue: 30,
        help: "Count the number of purchases, leads, or signups.",
        step: 1,
        min: 0,
      },
    ],
    example: {
      summary: "If you spend $1,200 and generate 30 acquisitions, your CPA is $40.",
      inputs: [
        { label: "Ad spend", value: "$1,200" },
        { label: "Acquisitions", value: "30" },
      ],
    },
    faq: [
      {
        question: "What counts as an acquisition?",
        answer:
          "It depends on the campaign goal. For ecommerce it may be a purchase, while for lead gen it may be a form fill, demo request, or signup.",
      },
      {
        question: "How do I lower CPA?",
        answer:
          "Lower CPCs, improve landing page conversion rate, and remove traffic sources that are not producing quality results.",
      },
      {
        question: "How is CPA different from CPL?",
        answer:
          "CPL is cost per lead. CPA is broader and can refer to any desired acquisition, including a sale, subscription, or app install.",
      },
    ],
    relatedSlugs: ["conversion-rate", "google-ads-budget", "roas"],
    compute: ({ adSpend, acquisitions }) => {
      const cpa = safeDivide(adSpend, acquisitions);
      return [
        {
          label: "CPA",
          value: toNumber(cpa),
          kind: "currency",
          helper: "Average cost for each acquisition.",
        },
        {
          label: "Acquisitions per $1,000",
          value: toNumber(safeDivide(acquisitions, adSpend) * 1000),
          kind: "number",
          helper: "How many acquisitions you get from $1,000 of spend.",
        },
        {
          label: "Spend per acquisition",
          value: toNumber(cpa),
          kind: "currency",
          helper: "Another view of the same acquisition cost.",
        },
      ];
    },
  },
  {
    slug: "cpm",
    name: "CPM Calculator",
    icon: "📢",
    description: "Calculate the cost to serve 1,000 impressions across your paid media campaigns.",
    metaDescription:
      "Use this CPM calculator to understand how much you are paying for 1,000 impressions and to benchmark media buying efficiency.",
    formula: "CPM = (Ad Spend / Impressions) x 1,000",
    formulaNote:
      "CPM is the standard way to compare the cost of exposure across channels and campaigns.",
    fields: [
      {
        key: "adSpend",
        label: "Ad spend",
        kind: "currency",
        defaultValue: 500,
        help: "Enter the spend for the campaign or ad set.",
        step: 10,
        min: 0,
      },
      {
        key: "impressions",
        label: "Impressions",
        kind: "number",
        defaultValue: 120000,
        help: "The total number of times the ad was shown.",
        step: 1000,
        min: 0,
      },
    ],
    example: {
      summary: "A $500 campaign that delivered 120,000 impressions has a CPM of $4.17.",
      inputs: [
        { label: "Ad spend", value: "$500" },
        { label: "Impressions", value: "120,000" },
      ],
    },
    faq: [
      {
        question: "Why does CPM change so much?",
        answer:
          "Audience quality, seasonality, competition, and creative performance can all push CPM up or down.",
      },
      {
        question: "Is lower CPM always better?",
        answer:
          "Not always. Cheap impressions are useful only if they reach the right audience and support your campaign goal.",
      },
      {
        question: "When should I use CPM?",
        answer:
          "CPM is most helpful for awareness campaigns, reach planning, and comparing media buying costs across channels.",
      },
    ],
    relatedSlugs: ["ctr", "facebook-ads-cost", "tiktok-ads-cost"],
    compute: ({ adSpend, impressions }) => {
      const cpm = safeDivide(adSpend * 1000, impressions);
      return [
        {
          label: "CPM",
          value: toNumber(cpm),
          kind: "currency",
          helper: "Cost for 1,000 impressions.",
        },
        {
          label: "Cost per impression",
          value: toNumber(safeDivide(adSpend, impressions)),
          kind: "currency",
          helper: "How much each single impression costs.",
        },
        {
          label: "Impressions per $1",
          value: toNumber(safeDivide(impressions, adSpend)),
          kind: "number",
          helper: "How many impressions you buy with one dollar.",
        },
      ];
    },
  },
  {
    slug: "ctr",
    name: "CTR Calculator",
    icon: "🖱️",
    description: "Find your click-through rate and see how many clicks you earn from each impression.",
    metaDescription:
      "Calculate click-through rate instantly and see whether your ad creative is earning the clicks you need.",
    formula: "CTR = (Clicks / Impressions) x 100",
    formulaNote:
      "CTR shows how compelling your ad is to the audience that sees it.",
    fields: [
      {
        key: "clicks",
        label: "Clicks",
        kind: "number",
        defaultValue: 420,
        help: "The number of clicks your ad received.",
        step: 1,
        min: 0,
      },
      {
        key: "impressions",
        label: "Impressions",
        kind: "number",
        defaultValue: 25000,
        help: "The number of times the ad was shown.",
        step: 1000,
        min: 0,
      },
    ],
    example: {
      summary: "420 clicks from 25,000 impressions gives you a 1.68% CTR.",
      inputs: [
        { label: "Clicks", value: "420" },
        { label: "Impressions", value: "25,000" },
      ],
    },
    faq: [
      {
        question: "What is a good CTR?",
        answer:
          "That depends on the platform, industry, and objective. The best benchmark is usually your own historical performance.",
      },
      {
        question: "Does CTR affect costs?",
        answer:
          "Yes. Strong CTR can improve relevance signals and often helps reduce CPCs on paid media platforms.",
      },
      {
        question: "How can I improve CTR?",
        answer:
          "Use stronger hooks, clearer offers, tighter audience targeting, and creative that matches the user's intent.",
      },
    ],
    relatedSlugs: ["cpm", "conversion-rate", "google-ads-budget"],
    compute: ({ clicks, impressions }) => {
      const ctr = safeDivide(clicks, impressions) * 100;
      return [
        {
          label: "CTR",
          value: toNumber(ctr),
          kind: "percent",
          helper: "Share of impressions that became clicks.",
        },
        {
          label: "Clicks per 1,000 impressions",
          value: toNumber(safeDivide(clicks, impressions) * 1000),
          kind: "number",
          helper: "Click volume normalized to 1,000 impressions.",
        },
        {
          label: "Unclicked impressions",
          value: toNumber(impressions - clicks),
          kind: "number",
          helper: "Impressions that did not turn into clicks.",
        },
      ];
    },
  },
  {
    slug: "conversion-rate",
    name: "Conversion Rate Calculator",
    icon: "✅",
    description: "Measure the percentage of clicks that become leads, signups, or sales.",
    metaDescription:
      "Calculate conversion rate in real time and evaluate how efficiently your traffic turns into outcomes.",
    formula: "Conversion Rate = (Conversions / Clicks) x 100",
    formulaNote:
      "Conversion rate helps you judge landing page quality and offer-market fit.",
    fields: [
      {
        key: "conversions",
        label: "Conversions",
        kind: "number",
        defaultValue: 78,
        help: "The number of desired actions completed.",
        step: 1,
        min: 0,
      },
      {
        key: "clicks",
        label: "Clicks",
        kind: "number",
        defaultValue: 1800,
        help: "The number of visitors or clicks that entered the funnel.",
        step: 1,
        min: 0,
      },
    ],
    example: {
      summary: "78 conversions from 1,800 clicks equals a 4.33% conversion rate.",
      inputs: [
        { label: "Conversions", value: "78" },
        { label: "Clicks", value: "1,800" },
      ],
    },
    faq: [
      {
        question: "What is a conversion?",
        answer:
          "A conversion is whatever action matters most to your campaign, such as a purchase, lead, app install, or booked call.",
      },
      {
        question: "How do I improve conversion rate?",
        answer:
          "Match the landing page to the ad promise, reduce friction, improve page speed, and test stronger calls to action.",
      },
      {
        question: "Should I optimize for conversion rate alone?",
        answer:
          "Not always. A higher conversion rate is great, but it should still produce quality leads or customers at a sustainable cost.",
      },
    ],
    relatedSlugs: ["cpa", "roas", "google-ads-budget"],
    compute: ({ conversions, clicks }) => {
      const rate = safeDivide(conversions, clicks) * 100;
      return [
        {
          label: "Conversion rate",
          value: toNumber(rate),
          kind: "percent",
          helper: "Share of clicks that converted.",
        },
        {
          label: "Conversions per 1,000 clicks",
          value: toNumber(safeDivide(conversions, clicks) * 1000),
          kind: "number",
          helper: "Expected conversions normalized to 1,000 clicks.",
        },
        {
          label: "Clicks per conversion",
          value: toNumber(safeDivide(clicks, conversions)),
          kind: "number",
          helper: "How many clicks you need for each conversion.",
        },
      ];
    },
  },
  {
    slug: "break-even-roas",
    name: "Break Even ROAS Calculator",
    icon: "⚖️",
    description: "Find the minimum ROAS you need to avoid losing money on a sale.",
    metaDescription:
      "Calculate break-even ROAS from your gross margin and average order value so you know the profitability threshold for your campaigns.",
    formula: "Break-even ROAS = 100 / Gross Margin %",
    formulaNote:
      "If your gross margin is 40%, your break-even ROAS is 2.5x.",
    fields: [
      {
        key: "averageOrderValue",
        label: "Average order value",
        kind: "currency",
        defaultValue: 100,
        help: "The typical revenue from one order.",
        step: 5,
        min: 0,
      },
      {
        key: "grossMargin",
        label: "Gross margin %",
        kind: "percent",
        defaultValue: 40,
        help: "Your gross margin after product and fulfillment costs.",
        step: 0.5,
        min: 0,
      },
    ],
    example: {
      summary: "With a $100 AOV and 40% gross margin, you can spend up to $40 per order and still break even.",
      inputs: [
        { label: "Average order value", value: "$100" },
        { label: "Gross margin", value: "40%" },
      ],
    },
    faq: [
      {
        question: "Why does break-even ROAS matter?",
        answer:
          "It tells you the minimum return needed to cover product costs and stay profitable before overhead is considered.",
      },
      {
        question: "Can break-even ROAS change by product?",
        answer:
          "Yes. Different products, bundles, and subscription plans often have different margins and therefore different break-even thresholds.",
      },
      {
        question: "Is break-even ROAS the same as target ROAS?",
        answer:
          "No. Break-even ROAS is the floor, while target ROAS is usually higher to leave room for profit and overhead.",
      },
    ],
    relatedSlugs: ["roas", "cpa", "email-marketing-roi"],
    compute: ({ averageOrderValue, grossMargin }) => {
      const breakEvenRoas = safeDivide(100, grossMargin);
      const maxAdSpend = averageOrderValue * safeDivide(grossMargin, 100);
      return [
        {
          label: "Break-even ROAS",
          value: toNumber(breakEvenRoas),
          kind: "multiple",
          helper: "Minimum return required to avoid losses.",
        },
        {
          label: "Max ad spend per order",
          value: toNumber(maxAdSpend),
          kind: "currency",
          helper: "The most you can pay to acquire one order.",
        },
        {
          label: "Gross profit per order",
          value: toNumber(maxAdSpend),
          kind: "currency",
          helper: "Profit available before ad spend is applied.",
        },
      ];
    },
  },
  {
    slug: "facebook-ads-cost",
    name: "Facebook Ads Cost Calculator",
    icon: "📘",
    description: "Estimate Facebook campaign spend and the impressions that budget can buy.",
    metaDescription:
      "Plan Facebook ad spend with this calculator. Estimate total budget, daily spend, and impressions from a CPM assumption.",
    formula: "Total Spend = Daily Budget x Campaign Days",
    formulaNote:
      "You can also estimate impressions from CPM to make media planning easier.",
    fields: [
      {
        key: "dailyBudget",
        label: "Daily budget",
        kind: "currency",
        defaultValue: 50,
        help: "How much you want to spend each day.",
        step: 5,
        min: 0,
      },
      {
        key: "campaignDays",
        label: "Campaign days",
        kind: "number",
        defaultValue: 30,
        help: "How long the campaign will run.",
        step: 1,
        min: 1,
      },
      {
        key: "cpm",
        label: "Estimated CPM",
        kind: "currency",
        defaultValue: 12.5,
        help: "Expected cost per 1,000 impressions.",
        step: 0.1,
        min: 0,
      },
    ],
    example: {
      summary: "A $50 daily budget over 30 days with a $12.50 CPM implies roughly 120,000 impressions.",
      inputs: [
        { label: "Daily budget", value: "$50" },
        { label: "Campaign days", value: "30" },
        { label: "Estimated CPM", value: "$12.50" },
      ],
    },
    faq: [
      {
        question: "What affects Facebook ad costs?",
        answer:
          "Audience competition, creative quality, placement mix, and seasonality all influence what you pay.",
      },
      {
        question: "Is Facebook cheaper than other channels?",
        answer:
          "Sometimes, but not always. Compare Facebook against your CPA, CPM, and ROAS goals instead of looking at price alone.",
      },
      {
        question: "Should I plan by daily budget or total budget?",
        answer:
          "Use daily budget to control pacing, then multiply by campaign length to understand the total planned spend.",
      },
    ],
    relatedSlugs: ["cpm", "ctr", "tiktok-ads-cost"],
    compute: ({ dailyBudget, campaignDays, cpm }) => {
      const totalSpend = dailyBudget * campaignDays;
      const impressions = safeDivide(totalSpend * 1000, cpm);
      return [
        {
          label: "Total spend",
          value: toNumber(totalSpend),
          kind: "currency",
          helper: "Planned spend for the full campaign.",
        },
        {
          label: "Estimated impressions",
          value: toNumber(impressions),
          kind: "number",
          helper: "Approximate impressions based on CPM.",
        },
        {
          label: "Daily spend",
          value: toNumber(dailyBudget),
          kind: "currency",
          helper: "Average amount spent each day.",
        },
      ];
    },
  },
  {
    slug: "tiktok-ads-cost",
    name: "TikTok Ads Cost Calculator",
    icon: "🎵",
    description: "Plan TikTok budget, total spend, and estimated impressions before you launch.",
    metaDescription:
      "Estimate TikTok ad spend, daily budget, and expected impressions using a simple CPM-based planning calculator.",
    formula: "Total Spend = Daily Budget x Campaign Days",
    formulaNote:
      "TikTok campaigns are often planned from a daily budget and then translated into expected reach using CPM.",
    fields: [
      {
        key: "dailyBudget",
        label: "Daily budget",
        kind: "currency",
        defaultValue: 60,
        help: "How much you are willing to spend per day.",
        step: 5,
        min: 0,
      },
      {
        key: "campaignDays",
        label: "Campaign days",
        kind: "number",
        defaultValue: 14,
        help: "Number of days the campaign will run.",
        step: 1,
        min: 1,
      },
      {
        key: "cpm",
        label: "Estimated CPM",
        kind: "currency",
        defaultValue: 8.5,
        help: "Projected cost per 1,000 impressions on TikTok.",
        step: 0.1,
        min: 0,
      },
    ],
    example: {
      summary: "A $60 daily budget for 14 days at an $8.50 CPM will spend $840 and buy about 98,823 impressions.",
      inputs: [
        { label: "Daily budget", value: "$60" },
        { label: "Campaign days", value: "14" },
        { label: "Estimated CPM", value: "$8.50" },
      ],
    },
    faq: [
      {
        question: "Why use CPM for TikTok planning?",
        answer:
          "CPM is a fast way to estimate reach and compare TikTok costs against other paid social platforms.",
      },
      {
        question: "Can I use this for creator campaigns?",
        answer:
          "Yes, but creator partnerships may include extra production or usage costs beyond media spend.",
      },
      {
        question: "How do I make TikTok spend more efficient?",
        answer:
          "Improve the first two seconds of the video, keep the offer simple, and test multiple creatives quickly.",
      },
    ],
    relatedSlugs: ["cpm", "ctr", "facebook-ads-cost"],
    compute: ({ dailyBudget, campaignDays, cpm }) => {
      const totalSpend = dailyBudget * campaignDays;
      const impressions = safeDivide(totalSpend * 1000, cpm);
      return [
        {
          label: "Total spend",
          value: toNumber(totalSpend),
          kind: "currency",
          helper: "Estimated campaign spend.",
        },
        {
          label: "Estimated impressions",
          value: toNumber(impressions),
          kind: "number",
          helper: "Projected reach based on CPM.",
        },
        {
          label: "Average daily impressions",
          value: toNumber(safeDivide(impressions, campaignDays)),
          kind: "number",
          helper: "Impressions you might see per day.",
        },
      ];
    },
  },
  {
    slug: "google-ads-budget",
    name: "Google Ads Budget Calculator",
    icon: "🔎",
    description: "Estimate the budget you need to buy the clicks and conversions you want on Google Ads.",
    metaDescription:
      "Plan your Google Ads budget with target clicks, max CPC, and campaign duration to estimate daily and total spend.",
    formula: "Budget = Target Clicks x Max CPC",
    formulaNote:
      "You can also translate that budget into expected conversions using a conversion rate assumption.",
    fields: [
      {
        key: "targetClicks",
        label: "Target clicks",
        kind: "number",
        defaultValue: 500,
        help: "How many clicks you want the campaign to deliver.",
        step: 10,
        min: 0,
      },
      {
        key: "maxCpc",
        label: "Max CPC",
        kind: "currency",
        defaultValue: 2.5,
        help: "The maximum amount you are willing to pay for a click.",
        step: 0.05,
        min: 0,
      },
      {
        key: "campaignDays",
        label: "Campaign days",
        kind: "number",
        defaultValue: 30,
        help: "How long the campaign should run.",
        step: 1,
        min: 1,
      },
      {
        key: "conversionRate",
        label: "Expected conversion rate %",
        kind: "percent",
        defaultValue: 4,
        help: "Estimated share of clicks that will convert.",
        step: 0.1,
        min: 0,
      },
    ],
    example: {
      summary: "For 500 clicks at a $2.50 CPC, you need a $1,250 budget, or about $41.67 per day over 30 days.",
      inputs: [
        { label: "Target clicks", value: "500" },
        { label: "Max CPC", value: "$2.50" },
        { label: "Campaign days", value: "30" },
      ],
    },
    faq: [
      {
        question: "What is max CPC?",
        answer:
          "It is the highest amount you want to pay for a single click in Google Ads auctions.",
      },
      {
        question: "How do I know if my budget is enough?",
        answer:
          "Compare your target clicks and CPC assumptions against your conversion goals and acceptable CPA.",
      },
      {
        question: "Does this calculator estimate conversions?",
        answer:
          "Yes. It uses the conversion rate you enter to estimate how many clicks may turn into results.",
      },
    ],
    relatedSlugs: ["cpa", "conversion-rate", "roas"],
    compute: ({ targetClicks, maxCpc, campaignDays, conversionRate }) => {
      const totalBudget = targetClicks * maxCpc;
      const dailyBudget = safeDivide(totalBudget, campaignDays);
      const estimatedConversions = targetClicks * safeDivide(conversionRate, 100);
      const costPerConversion = safeDivide(totalBudget, estimatedConversions);
      return [
        {
          label: "Total budget",
          value: toNumber(totalBudget),
          kind: "currency",
          helper: "Budget required to buy the target clicks.",
        },
        {
          label: "Daily budget",
          value: toNumber(dailyBudget),
          kind: "currency",
          helper: "Average spend per day over the campaign.",
        },
        {
          label: "Estimated cost per conversion",
          value: toNumber(costPerConversion),
          kind: "currency",
          helper: "Budget divided by the expected number of conversions.",
        },
      ];
    },
  },
  {
    slug: "email-marketing-roi",
    name: "Email Marketing ROI Calculator",
    icon: "✉️",
    description: "Model the return from your email campaign using list size, engagement, and revenue.",
    metaDescription:
      "Calculate email marketing ROI by estimating opens, clicks, conversions, revenue, costs, and the final return on investment.",
    formula: "ROI = ((Revenue - Cost) / Cost) x 100",
    formulaNote:
      "Email is often one of the highest-ROI channels because the cost per send is usually very low.",
    fields: [
      {
        key: "subscribers",
        label: "Subscribers",
        kind: "number",
        defaultValue: 10000,
        help: "How many people will receive the email.",
        step: 100,
        min: 0,
      },
      {
        key: "openRate",
        label: "Open rate %",
        kind: "percent",
        defaultValue: 35,
        help: "Expected share of recipients who open the email.",
        step: 0.1,
        min: 0,
      },
      {
        key: "clickRate",
        label: "Click rate %",
        kind: "percent",
        defaultValue: 4,
        help: "Expected share of opens that turn into clicks.",
        step: 0.1,
        min: 0,
      },
      {
        key: "conversionRate",
        label: "Conversion rate %",
        kind: "percent",
        defaultValue: 2.5,
        help: "Expected share of clicks that turn into conversions.",
        step: 0.1,
        min: 0,
      },
      {
        key: "averageOrderValue",
        label: "Average order value",
        kind: "currency",
        defaultValue: 80,
        help: "Average revenue per conversion.",
        step: 5,
        min: 0,
      },
      {
        key: "costPerSend",
        label: "Cost per send",
        kind: "currency",
        defaultValue: 0.01,
        help: "Email platform and send cost per subscriber.",
        step: 0.001,
        min: 0,
      },
    ],
    example: {
      summary:
        "Sending to 10,000 subscribers with a 35% open rate, 4% click rate, 2.5% conversion rate, and $80 AOV can generate strong ROI at a low send cost.",
      inputs: [
        { label: "Subscribers", value: "10,000" },
        { label: "Open rate", value: "35%" },
        { label: "Click rate", value: "4%" },
        { label: "Conversion rate", value: "2.5%" },
      ],
    },
    faq: [
      {
        question: "What makes email ROI so strong?",
        answer:
          "Once the list is built, the marginal cost of sending is low, so even modest conversion rates can produce a strong return.",
      },
      {
        question: "Should I track ROI or revenue?",
        answer:
          "Track both. Revenue shows scale, while ROI shows efficiency after costs are included.",
      },
      {
        question: "How do I improve email ROI?",
        answer:
          "Segment the list, improve subject lines, personalize content, and send offers that match recipient intent.",
      },
    ],
    relatedSlugs: ["roas", "conversion-rate", "break-even-roas"],
    compute: ({
      subscribers,
      openRate,
      clickRate,
      conversionRate,
      averageOrderValue,
      costPerSend,
    }) => {
      const opens = subscribers * safeDivide(openRate, 100);
      const clicks = opens * safeDivide(clickRate, 100);
      const conversions = clicks * safeDivide(conversionRate, 100);
      const revenue = conversions * averageOrderValue;
      const cost = subscribers * costPerSend;
      const roi = safeDivide(revenue - cost, cost) * 100;
      return [
        {
          label: "Revenue",
          value: toNumber(revenue),
          kind: "currency",
          helper: "Estimated campaign revenue.",
        },
        {
          label: "ROI",
          value: toNumber(roi),
          kind: "percent",
          helper: "Profit relative to cost.",
        },
        {
          label: "Total cost",
          value: toNumber(cost),
          kind: "currency",
          helper: "Cost to send the campaign to your list.",
        },
      ];
    },
  },
  ...additionalCalculators,
];

export const calculatorSlugs = calculators.map((calculator) => calculator.slug);

export function getCalculatorBySlug(slug: string) {
  return calculators.find((calculator) => calculator.slug === slug);
}
